name: Build Flutter iOS

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-ios:
    runs-on: macos-latest

    steps:
      # 1️⃣ Haal de code op
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ Installeer Flutter
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.13.0' # of jouw versie

      # 3️⃣ Install dependencies
      - name: Get Flutter dependencies
        run: flutter pub get

      # 4️⃣ Build voor iOS simulator (geen codesign nodig)
      - name: Build iOS (simulator)
        run: flutter build ipa

      # 5️⃣ Optioneel: archiveer artifacts
      - name: Archive build
        uses: actions/upload-artifact@v4
        with:
          name: ios-simulator-build
          path: build/ios/iphonesimulator
