name: Flutter Xcode Fake-Sign Build

on: 
  push:
  pull_request:
  workflow_dispatch:
    inputs: 
      release__nightly:
        description: Create a nightly release
        type: boolean
        required: false

jobs:
  build:
    name: Build Flutter IPA (unsigned)
    runs-on: macos-latest
    env:
      scheme: Runner
      archive_path: build/ios/archive
    outputs:
      scheme: ${{ steps.set_scheme.outputs.scheme }}
      archive_path: ${{ env.archive_path }}

    steps:
      - uses: actions/checkout@v3

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.35.3'
          channel: stable

      - name: Get Flutter dependencies
        run: flutter pub get

      - name: Set Scheme
        id: set_scheme
        run: |
          echo "scheme=$scheme" >> $GITHUB_OUTPUT

      - name: Build unsigned IPA
        run: flutter build ipa --no-codesign

      - name: Tar Build Artifact
        run: tar -cvf "$archive_path.xcarchive.tar" "$archive_path/Runner.xcarchive"

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.archive_path }}.xcarchive.tar
          path: ${{ env.archive_path }}.xcarchive.tar

  package:
    name: Create fake-signed IPA
    runs-on: macos-latest
    needs: [build]
    permissions:
      contents: write
    env:
      scheme: ${{ needs.build.outputs.scheme }}
      archive_path: ${{ needs.build.outputs.archive_path }}
    outputs:
      artifact: ${{ env.scheme }}.ipa

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Download a Build Artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ env.archive_path }}.xcarchive.tar

      - name: Extract Build Artifact
        run: tar -xf "$archive_path.xcarchive.tar"

      - name: Install ldid
        run: brew install ldid

      - name: Fakesign
        run: |
          APP_PATH="$archive_path/Runner.xcarchive/Products/Applications/$scheme.app"
          echo "Signing app at $APP_PATH"
          find "$APP_PATH" -type d -path '*/Frameworks/*.framework' -exec ldid -Sentitlements.xml {} \;
          ldid -Sentitlements.xml "$APP_PATH"

      - name: Create IPA
        run: |
          mkdir -p Payload
          cp -r "$archive_path/Runner.xcarchive/Products/Applications/$scheme.app" Payload/
          zip -r "$scheme.ipa" Payload -x "._*" -x ".DS_Store" -x "__MACOSX"

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.scheme }}.ipa
          path: ${{ env.scheme }}.ipa
